### ISSUE TITLE
Suggestion & Ask

### ISSUE THREAD

**Issue by chisi21** [Kygekraqmak/KygekRanksUI#1]
Can I edit config realtime? without having to reload / restart the server if you change the config.

if not possible, please add the edit config feature in realtime: D

thanks~

**Comment by KygekDev** [comment]
Yes,

Every changes in the config will automatically be applied to the plugin the next time someone use the /ranks command. The plugin can also detect for missing config file to prevent crashes.

Regards.

**Comment by chisi21** [comment]
THANKSS :D

**Comment by KygekDev** [comment]
Closed issue because it is already resolved and I forgot to close it.
