### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by AirLeMineral** [Kygekraqmak/KygekRanksUI#2]
This plugin is great, if you don't mind I want a request to add a config image url on each button ...
so i can add a custom image url for each button :D 
Good Job!

**Comment by KygekDev** [comment]
Thanks for the feedback, I'll working on it soon!

**Comment by AirLeMineral** [comment]
So cool... thanks :D

**Comment by KygekDev** [comment]
Closed issue because this feature has been implemented since over a year ago (In other words, I forgot to close this issue).
