### ISSUE TITLE
Question of config.yml

### ISSUE THREAD

**Issue by UnEnanoMas** [Kygekraqmak/KygekRanksUI#3]
Hi, thanks so much for making this plugin, it's great.

I wanted to know how I can go down to the next line without having to finish the entire text.

That is to say:

1.- For this range it is necessary to have 5h on the server
2.- It is necessary to have the Veteran rank or higher
3.- ...

**Comment by KygekDev** [comment]
You can use `\n` to break into a new line.

I apologize because I forgot to tell that you can use `\n` to break into a new line in config.yml.

Regards.

**Comment by UnEnanoMas** [comment]
ty! <3
