### ISSUE TITLE
Error in pocketmine

### ISSUE THREAD

**Issue by FlamptX** [Kygekraqmak/KygekRanksUI#4]
When I use the plugin in a pocketmine app I get this: server thread ERROR could not resolve host: poggit.pmmp.io
How do i fix that?

**Comment by aminozomty** [comment]
Can you dm me on discord aminozomty#5662 do i can see to fix it and try to help you

**Comment by KygekDev** [comment]
**Dear @dinko13579,**

Poggit might be down when you used the KygekRanksUI plugin. Please try to start your server again. If the issue still persists, please contact aminozomty#5662 via Discord.

**Best regards,**
KygekDev

**Comment by FlamptX** [comment]
> Can you dm me on discord aminozomty#5662 do i can see to fix it and try to help you

I tried to sent a friend request on discord but you have to add me first Flampt#4460
