### ISSUE TITLE
Economy Money RankSystem

### ISSUE THREAD

**Issue by ghost** [Kygekraqmak/KygekRanksUI#6]
How can i added the Price of the Rank ?

**Comment by NhanAZ** [comment]
> How can i added the Price of the Rank ?

I think you should join the discord server for help with this issue
[KygekTeam Discord](https://discord.gg/wmnV3Dyf)

**Comment by KygekDev** [comment]
> How can i added the Price of the Rank ?

This plugin is only for showing ranks, not a rank system plugin. Closing the issue...
